# Generated by Django 4.0.4 on 2023-02-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('UserID', models.CharField(max_length=200)),
                ('meetName', models.CharField(max_length=200)),
            ],
        ),
    ]
